### ISSUE TITLE
Readme mangler nogle ting...

### ISSUE THREAD

**Issue by Robotto** [MightGit/FodboldturV2#1]
Fedt med links til billederne, men prøv at få dem indsat i readme filen 

Det er noget med: `![se et flot billede](relativ/sti/til/billedet.jpg)` (eller bare google markdown insert image)

Jeg mangler et link til jeres trello board.

**Comment by MightGit** [comment]
Dette er fixet!

**Comment by Robotto** [comment]
Hov... Er det meningen at det her issue skal være åbnet igen?

**Comment by MightGit** [comment]
Missclick!
